package ch.mofobo.foodscanner.domain.model

import com.squareup.moshi.Json

data class Nutrients(
    val biotin: NutrientInfo?,
    val calcium: NutrientInfo?,
    val carbohydrates: NutrientInfo?,
    val cholesterol: NutrientInfo?,
    val energy: NutrientInfo?,
    val energy_kcal: NutrientInfo?,
    val fat: NutrientInfo?,
    val fiber: NutrientInfo?,
    @field:Json(name = "folic_acid") val folicAcid: NutrientInfo?,
    val fructose: NutrientInfo?,
    val glucose: NutrientInfo?,
    val iodine: NutrientInfo?,
    val iron: NutrientInfo?,
    val lactose: NutrientInfo?,
    val magnesium: NutrientInfo?,
    @field:Json(name = "monounsaturated_fatty_acids") val monounsaturatedFattyAcids: NutrientInfo?,
    @field:Json(name = "omega-3_fatty_acids") val omega_3_fatty_acids: NutrientInfo?,
    @field:Json(name = "omega-6_fatty_acids") val omega_6_fatty_acids: NutrientInfo?,
    val phosphorus: NutrientInfo?,
    val polyols: NutrientInfo?,
    @field:Json(name = "polyunsaturated_fatty_acids") val polyunsaturatedFattyAcids: NutrientInfo?,
    val protein: NutrientInfo?,
    @field:Json(name = "provitamin_a_-carotene") val provitaminACarotene: NutrientInfo?,
    val saccharose: NutrientInfo?,
    val salt: NutrientInfo?,
    val saturated_fat: NutrientInfo?,
    val selenium: NutrientInfo?,
    val sodium: NutrientInfo?,
    val sugars: NutrientInfo?,
    @field:Json(name = "vitamin_a") val vitaminA: NutrientInfo?,
    @field:Json(name = "vitamin_b12_cobalamin") val vitaminB12Cobalamin: NutrientInfo?,
    @field:Json(name = "vitamin_b1_thiamin") val vitaminB1Thiamin: NutrientInfo?,
    @field:Json(name = "vitamin_b2_riboflavin") val vitaminB2Riboflavin: NutrientInfo?,
    @field:Json(name = "vitamin_b3_niacin") val vitaminB3Niacin: NutrientInfo?,
    @field:Json(name = "vitamin_b5_panthothenic_acid") val vitaminB5PanthothenicAcid: NutrientInfo?,
    @field:Json(name = "vitamin_b6_pyridoxin") val vitaminB6Pyridoxin: NutrientInfo?,
    @field:Json(name = "vitamin_c_ascorbic_acid") val vitaminCAscorbicAcid: NutrientInfo?,
    @field:Json(name = "vitamin_d_cholacalciferol") val vitaminDCholacalciferol: NutrientInfo?,
    @field:Json(name = "vitamin_e_tocopherol") val vitaminETocopherol: NutrientInfo?,
    @field:Json(name = "vitamin_k") val vitaminK: NutrientInfo?,
    val zinco: NutrientInfo?
)